blank_issues_enabled: true
contact_links:
  - name: View documentation
    url: https://lingui.dev
    about: Check the official docs for answers to common questions
  - name: Check compatibility table
    url: https://github.com/lingui/swc-plugin#compatibility
    about: Check the compatibility table for the SWC plugin
  - name: Chat on Discord
    url: https://discord.gg/gFWwAYnMtA
    about: Join the Lingui community on Discord
